config/routes.rb
Simfy::Application.routes.draw do

  get "search/index"

  devise_for :user do
    get "/login", :to => "devise/sessions#new"      # Add a custom sign in route for user sign in
    get "/logout", :to => "devise/sessions#destroy" # Add a custom sing out route for user sign out
    get "/register", :to => "devise/registrations#new" # Add a Custom Route for Registrations
  end

  resources :artists, :only => [:show]
  resources :albums, :only => [:show]
  resources :users, :only => [:index, :show] do
    resources :artists
    resources :albums do
      resources :tracks
    end
  end

  match '/artists' => 'artists#public_list', :as => :public_artists_list
  match '/albums' => 'albums#public_list', :as => :public_albums_list
  match '/search' => 'search#index', :as => :search

  root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  default_scope order('label ASC')
  mount_uploader :cover, CoverUploader
  attr_accessible :artist_id, :cover,:label, :release_at, :review
  belongs_to :artist
  has_many :tracks ,:dependent => :destroy
  has_many :comments ,:dependent => :destroy

  #for test purpose simple duration format
  def duration
     (Time.mktime(0)+(tracks.map(&:duration).inject(:+) || 0)).strftime("%H:%M:%S")
  end

  searchable do
    text :label,:review
  end

  scope :by_letter,lambda{ |letter| letter ? where("label like ?", "#{letter}%" ) : scoped}
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  default_scope order('name ASC')
  attr_accessible :biography, :name
  has_many :albums ,:dependent => :destroy
  belongs_to :user

  searchable do
    text :name,:biography
  end
  scope :by_letter,lambda{ |letter| letter ? where("name like ?", "#{letter}%" ) : scoped}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :title ,:duration
  belongs_to :album
  #for test purpose simple duration format
  def duration_label
     (Time.mktime(0)+self[:duration]).strftime("%H:%M:%S")
  end

  def duration=(value)
    super Time.parse(value).seconds_since_midnight.to_i
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope order('username ASC')
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :artists,:dependent => :destroy
  has_many :albums ,:through => :artists
  has_many :tracks ,:through => :albums
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:username

  validates_format_of :username, :with => /^[a-zA-Z0-9]+$/i, :on=>:create
  validates_length_of :username, :within => 4..20, :on=>:create
  validates_uniqueness_of :username, :on=>:create

  scope :by_letter,lambda{ |letter| letter ? where("username like ?", "#{letter}%" ) : scoped}

  def to_param
    username
  end


end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  enable_authorization
end

app/controllers/albums_controller.rb
class AlbumsController < AccountController
  load_and_authorize_resource
  #this is just simple for test purpose. Can be done with separate controllers thought user scope
  def public_list
    @albums = Album.by_letter(params[:letter])
    render :action => :index
  end

  def index
    @albums = current_user.albums.by_letter(params[:letter])
  end

  def show
    @album ||= Album.find(params[:id])
  end

  def new
    @album ||= current_user.albums.build
  end

  def edit
    @album ||= current_user.albums.find(params[:id])
  end

  def create
    @album ||= current_user.albums.create(params[:album])
    respond_with @album ,:location=>current_user ? user_albums_path(current_user) : public_albums_list_path
  end

  def update
    @album ||= current_user.albums.find(params[:id])
    @album.update_attributes(params[:album])
    respond_with @album ,:location=>current_user ? user_albums_path(current_user) : public_albums_list_path
  end

  def destroy
    @album ||= current_user.albums.find(params[:id])
    @album.try(:destroy)
    redirect_to current_user ? user_albums_path(current_user) : public_albums_list_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  respond_to :html

  def after_sign_in_path_for(scope)
    root_path
  end

  def after_sign_out_path_for(scope)
    new_session_path scope
  end



end

app/controllers/artists_controller.rb
class ArtistsController < AccountController
  load_and_authorize_resource
  #this is just simple for test purpose. Can be done with separate controllers thought user scope
  def public_list
    @artists = Artist.by_letter(params[:letter])
    render :action => :index
  end

  def index
    @artists = current_user.artists.by_letter(params[:letter])
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = current_user.artists.build
  end

  def edit
    @artist = current_user.artists.find(params[:id])
  end

  def create
    @artist = current_user.artists.create(params[:artist])
    respond_with @artist, :location => current_user ? user_artists_path(current_user) : public_artist_list_path
  end

  def update
    @artist = current_user.artists.find(params[:id])
    @artist.update_attributes(params[:artist]) if @artist
    respond_with @artist, :location => current_user ? user_artists_path(current_user) : public_artist_list_path
  end


  def destroy
    current_user.artists.find(params[:id]).try(:destroy)
    redirect_to artists_path
  end
end

app/controllers/comments_controller.rb
class CommentController < AccountController
  before_filter :fetch_album


  def create
    @album.comments.create(params[:comment])
    redirect_to album_path(@album)
  end

  def update
    @comment = @album.comments.find(params[:id])
    @comment.update_attributes(params[:comment]) if @comment
    redirect_to artists_path
  end


  def destroy
    @album.comments.find(params[:id]).try(:destroy)
    redirect_to artists_path
  end

  private

  def fetch_album
    @album = current_user.albums.find(params[:album_id])
    unless @album
      flash.notice "We couldn't find that record!'"
      redirect_to artists_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @search = Sunspot.search(Album, Artist) do
      keywords params[:q]
    end
    @results = @search.results
  end
end

app/controllers/tracks_controller.rb
class TracksController < AccountController
  load_and_authorize_resource :album
  load_and_authorize_resource :track,:through=>:album

  def index
    @tracks = @album.tracks
  end

  def new
    @track = @album.tracks.build
  end

  def edit
    @track = @album.tracks.find(params[:id])
  end

  def create
    @track = @album.tracks.create(params[:track])
    respond_with @track ,:location=> album_path(@album)
  end

  def update
    @track = @album.tracks.find(params[:id])
    @track.update_attributes(params[:track]) if @track
    respond_with @track
  end


  def destroy
    @album.tracks.find(params[:id]).try(:destroy)
    redirect_to album_path(@album)
  end

  private

  def fetch_album
    @album = current_user.albums.find(params[:album_id])
    unless @album
      flash.notice "We couldn't find that record!'"
      redirect_to artists_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.by_letter(params[:letter]).includes(:artists,:albums)
  end

  def show
    @user = User.find_by_username(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end

  def alphabet_links
    ('A'..'Z').collect { |l| link_to( l, url_for(:letter=>l),:class=>'btn')}.join('').html_safe << link_to( 'all', url_for(),:class=>'btn')
  end

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.haml
= simple_form_for [current_user,@album], :html => {:class => 'form-horizontal' } do |f|
  -if @album.errors.any?
    #error_explanation
      %h2= "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
      %ul
        - @album.errors.full_messages.each do |msg|
          %li= msg
  = f.association :artist
  = f.input :label
  = f.input :review,  :input_html => { :rows => 4 }
  = f.input :release_at
  = f.input :cover
  = f.submit 'Save'

app/views/albums/edit.html.haml
%h1 Editing album

= render 'form'

= link_to 'Show', user_album_path(current_user,@album)
\|
= link_to 'Back', user_albums_path(current_user,@album)

app/views/albums/index.html.haml
- content_for :header do
  %h1=  "Albums"
  %div.well
    = alphabet_links
%table.table.table-bordered.table-striped
  %tr
    %th Artist
    %th Label
    %th Label
    %th Release at
    %th Duration
    %th
    %th
    %th

  - @albums.each do |album|
    %tr
      %td= album.artist.name
      %td= image_tag(album.cover.thumb.url)
      %td= album.label
      %td= album.release_at
      %td= album.duration
      %td
        - if can?( :read, album)
          = link_to album_path(album) do
            %i.icon-tag
            Show
      %td
        - if can?( :manage, album)
          = link_to  edit_user_album_path(current_user,album) do
            %i.icon-pencil
            Edit
      %td
        - if can?( :manage, album)
          = link_to  user_album_path(current_user,album), :confirm => 'Are you sure?', :method => :delete do
            %i.icon-trash
            Delete



%br
- if  can?( :create, :albums)
  = link_to 'New Album', new_user_album_path(current_user) ,:class => 'btn btn-primary'
%br

app/views/albums/new.html.haml
- content_for :header do
  %h1=  "New Album"
= render 'form'

= link_to 'Back', albums_path

app/views/albums/show.html.haml
- content_for :header do
  %h1=  "Album #{@album.label}"
  %h2=  "Album #{@album.label}"
%p#notice= notice

%p
  %b Artist:
  = @album.artist_id

%p
  %b Review:
  = @album.review
%p
  %b Release at:
  = @album.release_at
%p
  %b Duration:
  = @album.duration

%p
  %b Number of songs:
  = @album.tracks.count
- if can? :manage, @album
  = link_to 'Edit', edit_user_album_path(current_user,@album)
  \|
= link_to 'Back', user_albums_path(current_user)

%hr
%table.table.table-bordered.table-striped
  %tr
    %th Title
    %th Duration
    %th
    %th

  - @album.tracks.each do |track|
    %tr
      %td= track.title
      %td= track.duration
      %td
        - if can?( :manage, track)
          = link_to  edit_user_album_track_path(current_user,@album,track) do
            %i.icon-pencil
            Edit
      %td
        - if can?( :manage, track)
          = link_to   user_album_track_path(current_user,@album,track), :confirm => 'Are you sure?', :method => :delete do
            %i.icon-trash
            Delete


%br
- if  can?( :create, :tracks)
  = link_to 'New Track', new_user_album_track_path(current_user,@album) ,:class => 'btn btn-primary'
%br

app/views/artists/_form.html.haml
= simple_form_for [current_user,@artist] do |f|
  -if @artist.errors.any?
    #error_explanation
      %h2= "#{pluralize(@artist.errors.count, "error")} prohibited this artist from being saved:"
      %ul
        - @artist.errors.full_messages.each do |msg|
          %li= msg
  = f.input :name
  = f.input :biography
  = f.submit 'Save'

app/views/artists/edit.html.haml
- content_for :header do
  %h1 Editing artist

= render 'form'

= link_to 'Show', user_artist_path(current_user,@artist)
\|
= link_to 'Back', user_artists_path(current_user)

app/views/artists/index.html.haml
- content_for :header do
  %h1=  "Artists"
  %div.well
    = alphabet_links
%table.table.table-bordered.table-striped
  %tr
    %th Name
    %th Biography
    %th
    %th
    %th

  - @artists.each do |artist|
    %tr
      %td= artist.name
      %td= artist.biography
      %td
        - if can?( :read, artist)
          = link_to artist_path(artist) do
            %i.icon-tag
            Show
      %td
        - if can?( :manage, artist)
          = link_to  edit_user_artist_path(current_user,artist) do
            %i.icon-pencil
            Edit
      %td
        - if can?( :manage, artist)
          = link_to  user_artist_path(current_user,artist), :confirm => 'Are you sure?', :method => :delete do
            %i.icon-trash
            Delete



%br
- if  can?( :create, :artists)
  = link_to 'New Artist', new_user_artist_path(current_user),:class=>'btn btn-primary'

app/views/artists/new.html.haml
- content_for :header do
  %h1=  "New Artist"
= render 'form'

= link_to 'Back', user_artists_path(current_user)

app/views/artists/show.html.haml
- content_for :header do
  %h1=  "Artist #{@artist.name}"
%p#notice= notice


%p
  %b Biography:
  = @artist.biography
- if can? :manage, @artist
  = link_to 'Edit', edit_user_artist_path(current_user,@artist)
  \|
= link_to 'Back', user_artists_path(current_user)

app/views/search/index.html.haml
%h1 Search#index
- if @search
  - @search.results.each do |record|
    - if record.is_a?(Album)
      %br
      = link_to record.label, user_album_path(current_user,record)

    - if record.is_a?(Artist)
      %br
      = record.name

app/views/tracks/_form.html.haml
= simple_form_for [current_user,@album,@track] do |f|
  -if @track.errors.any?
    #error_explanation
      %h2= "#{pluralize(@track.errors.count, "error")} prohibited this track from being saved:"
      %ul
        - @track.errors.full_messages.each do |msg|
          %li= msg

  = f.input :title
  = f.input :duration,:as=>:string
  = f.submit 'Save'

app/views/tracks/edit.html.haml
%h1 Editing track

= render 'form'

= link_to 'Show', @track
\|
= link_to 'Back', tracks_path

app/views/tracks/index.html.haml
%h1 Listing tracks

%table
  %tr
    %th Label
    %th Duration
    %th
    %th

  - @tracks.each do |track|
    %tr
      %td= track.title
      %td= track.duration_label
      %td= link_to 'Edit', edit_album_track_path(@album,track)
      %td= link_to 'Destroy', album_track_path(@album,track), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Track', new_album_track_path

app/views/tracks/new.html.haml
%h1 New track

= render 'form'

= link_to 'Back', user_album_tracks_path(current_user,@album)

app/views/tracks/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_track_path(@track)
\|
= link_to 'Back', tracks_path

app/views/users/index.html.haml
- content_for :header do
  %h1=  "Users"
  %div.well
    = alphabet_links


- @users.each do |user|
  %h3
    = link_to user.username, user_path(user)
  %table.table.table-bordered.table-striped
    %thead
      %th{:width=>"40%"}
      %th{:width=>"60%"}

    %tbody
      - user.albums.each do |album|
        %tr
          %td
            = album.label
            %br
            = image_tag(album.cover.thumb.url)
          %td
            %ol
              - album.tracks.each do |track|
                %li
                  %span= track.title

app/views/users/show.html.haml
- content_for :header do
  %h1=  "Users"

  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th
        %th  Label
      %tbody
        - @user.albums.each do |album|
          %tr
            %td= image_tag(album.cover.thumb.url)
            %td= album.label