config/routes.rb
Simfy::Application.routes.draw do

  get "search/index"

  devise_for :user do
    get "/login", :to => "devise/sessions#new"      # Add a custom sign in route for user sign in
    get "/logout", :to => "devise/sessions#destroy" # Add a custom sing out route for user sign out
    get "/register", :to => "devise/registrations#new" # Add a Custom Route for Registrations
  end

  resources :artists, :only => [:show]
  resources :albums, :only => [:show]
  resources :users, :only => [:index, :show] do
    resources :artists
    resources :albums do
      resources :tracks
    end
  end

  match '/artists' => 'artists#public_list', :as => :public_artists_list
  match '/albums' => 'albums#public_list', :as => :public_albums_list
  match '/search' => 'search#index', :as => :search

  root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  default_scope order('label ASC')
  mount_uploader :cover, CoverUploader
  attr_accessible :artist_id, :cover,:label, :release_at, :review
  belongs_to :artist
  has_many :tracks ,:dependent => :destroy
  has_many :comments ,:dependent => :destroy

  #for test purpose simple duration format
  def duration
     (Time.mktime(0)+(tracks.map(&:duration).inject(:+) || 0)).strftime("%H:%M:%S")
  end

  searchable do
    text :label,:review
  end

  scope :by_letter,lambda{ |letter| letter ? where("label like ?", "#{letter}%" ) : scoped}
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  default_scope order('name ASC')
  attr_accessible :biography, :name
  has_many :albums ,:dependent => :destroy
  belongs_to :user

  searchable do
    text :name,:biography
  end
  scope :by_letter,lambda{ |letter| letter ? where("name like ?", "#{letter}%" ) : scoped}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :title ,:duration
  belongs_to :album
  #for test purpose simple duration format
  def duration_label
     (Time.mktime(0)+self[:duration]).strftime("%H:%M:%S")
  end

  def duration=(value)
    super Time.parse(value).seconds_since_midnight.to_i
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope order('username ASC')
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :artists,:dependent => :destroy
  has_many :albums ,:through => :artists
  has_many :tracks ,:through => :albums
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:username

  validates_format_of :username, :with => /^[a-zA-Z0-9]+$/i, :on=>:create
  validates_length_of :username, :within => 4..20, :on=>:create
  validates_uniqueness_of :username, :on=>:create

  scope :by_letter,lambda{ |letter| letter ? where("username like ?", "#{letter}%" ) : scoped}

  def to_param
    username
  end


end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  enable_authorization
end

app/controllers/albums_controller.rb
class AlbumsController < AccountController
  load_and_authorize_resource
  #this is just simple for test purpose. Can be done with separate controllers thought user scope
  def public_list
    @albums = Album.by_letter(params[:letter])
    render :action => :index
  end

  def index
    @albums = current_user.albums.by_letter(params[:letter])
  end

  def show
    @album ||= Album.find(params[:id])
  end

  def new
    @album ||= current_user.albums.build
  end

  def edit
    @album ||= current_user.albums.find(params[:id])
  end

  def create
    @album ||= current_user.albums.create(params[:album])
    respond_with @album ,:location=>current_user ? user_albums_path(current_user) : public_albums_list_path
  end

  def update
    @album ||= current_user.albums.find(params[:id])
    @album.update_attributes(params[:album])
    respond_with @album ,:location=>current_user ? user_albums_path(current_user) : public_albums_list_path
  end

  def destroy
    @album ||= current_user.albums.find(params[:id])
    @album.try(:destroy)
    redirect_to current_user ? user_albums_path(current_user) : public_albums_list_path
  end
end

app/controllers/artists_controller.rb
class ArtistsController < AccountController
  load_and_authorize_resource
  #this is just simple for test purpose. Can be done with separate controllers thought user scope
  def public_list
    @artists = Artist.by_letter(params[:letter])
    render :action => :index
  end

  def index
    @artists = current_user.artists.by_letter(params[:letter])
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = current_user.artists.build
  end

  def edit
    @artist = current_user.artists.find(params[:id])
  end

  def create
    @artist = current_user.artists.create(params[:artist])
    respond_with @artist, :location => current_user ? user_artists_path(current_user) : public_artist_list_path
  end

  def update
    @artist = current_user.artists.find(params[:id])
    @artist.update_attributes(params[:artist]) if @artist
    respond_with @artist, :location => current_user ? user_artists_path(current_user) : public_artist_list_path
  end


  def destroy
    current_user.artists.find(params[:id]).try(:destroy)
    redirect_to artists_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @search = Sunspot.search(Album, Artist) do
      keywords params[:q]
    end
    @results = @search.results
  end
end

app/controllers/tracks_controller.rb
class TracksController < AccountController
  load_and_authorize_resource :album
  load_and_authorize_resource :track,:through=>:album

  def index
    @tracks = @album.tracks
  end

  def new
    @track = @album.tracks.build
  end

  def edit
    @track = @album.tracks.find(params[:id])
  end

  def create
    @track = @album.tracks.create(params[:track])
    respond_with @track ,:location=> album_path(@album)
  end

  def update
    @track = @album.tracks.find(params[:id])
    @track.update_attributes(params[:track]) if @track
    respond_with @track
  end


  def destroy
    @album.tracks.find(params[:id]).try(:destroy)
    redirect_to album_path(@album)
  end

  private

  def fetch_album
    @album = current_user.albums.find(params[:album_id])
    unless @album
      flash.notice "We couldn't find that record!'"
      redirect_to artists_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.by_letter(params[:letter]).includes(:artists,:albums)
  end

  def show
    @user = User.find_by_username(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end

  def alphabet_links
    ('A'..'Z').collect { |l| link_to( l, url_for(:letter=>l),:class=>'btn')}.join('').html_safe << link_to( 'all', url_for(),:class=>'btn')
  end

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Simfy
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Simfy",root_path,:class=>'brand'
          .nav-collapse
            %ul.nav
              %li
                = link_to "Users",users_path
              %li
                = link_to "Artist",public_artists_list_path
              %li
                = link_to "Albums",public_albums_list_path

            %form.navbar-search.pull-left{:action => search_path,:method=>:get}
              %input.search-query.span2{:placeholder => "Search", :type => "text",:name=>'q'}
            %ul.nav.pull-right
              - if current_user
                %li
                  = link_to "My Albums",user_albums_path(current_user)
                %li
                  = link_to "My Artists",user_artists_path(current_user)
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href =>'#'}
                    = current_user.username
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "My Account", user_path(current_user)
                    %li
                      = link_to "Sign out", logout_path
              - else
                %li
                  = link_to "Sign in", new_user_session_path
                %li.divider-vertical
                %li
                  = link_to "Sign up", new_user_registration_path



    %div.container
      %div.flash-messages-container
      - flash.each do |key, value|
        %div{:class => "#{flash_class(key)} fade in"}
          %a.close{"data-dismiss" => "alert", :href => "#"} ×
          = value
      %header.jumbotron.subhead
        =  yield(:header)
      = yield